### ISSUE TITLE
About the output of 3D-BoundingBox?

### ISSUE THREAD

**Issue by Stephen-ThreeD** [nhonth/visualize-3D-BoundingBox#1]
I have noticed that your code can plot results of https://github.com/fuenwang/3D-BoundingBox. 
And can you help me to understand what should we save as the results of https://github.com/fuenwang/3D-BoundingBox?

**Comment by nhonth** [comment]
Were you able to train the model? If so, you'll need to save the model file (.pkl) and the config file (config.yaml). These two files and the code will let you reconstruct the neural net (you can follow the code in its Eval.py file to see how it's done).

Given an image (from KITTI) and an object bounding box (2D), you can use the reconstructed model to estimate the object dimensions (width, height, and length) and local angle. In order to draw the 3D bounding box, the missing piece of information is 3D location of the object. The notebook in this repo shows how to do that.

Hope it helps.
